# Generated by Django 5.2.11 on 2026-02-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nom_entreprise',
            field=models.CharField(blank=True, default='', help_text='Obligatoire pour les comptes Pro', max_length=150),
        ),
    ]
