# Generated by Django 5.2.11 on 2026-02-20 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('source_media', models.URLField(blank=True, help_text="Lien vers l'article source")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Infos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleNouveaute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('lien_redirection', models.URLField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pro_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nouveautes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nouveauté',
                'verbose_name_plural': 'Nouveautés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticlePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('lien_promo', models.URLField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pro_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo',
                'verbose_name_plural': 'Promos',
                'ordering': ['-created_at'],
            },
        ),
    ]
