# Generated by Django 5.2.11 on 2026-03-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubriques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='articlenouveaute',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='articlepromo',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
