# Generated by Django 5.2.11 on 2026-02-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.IntegerField(default=0)),
                ('prix_label', models.CharField(blank=True, help_text='Ex: 15 000 XPF, Gratuit, À débattre', max_length=50)),
                ('categorie', models.CharField(choices=[('vehicules', 'Véhicules'), ('immobilier', 'Immobilier'), ('electronique', 'Électronique'), ('emploi', 'Emploi'), ('services', 'Services'), ('autres', 'Autres')], max_length=50)),
                ('localisation', models.CharField(default='Papeete', max_length=100)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('modere', 'Modéré'), ('vendu', 'Vendu'), ('expire', 'Expiré')], default='actif', max_length=20)),
                ('boost', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-boost', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_nom', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_tel', models.CharField(blank=True, max_length=20)),
                ('contenu', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
