# Generated by Django 5.2.11 on 2026-02-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandePublicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('entreprise', models.CharField(blank=True, max_length=200)),
                ('emplacement_souhaite', models.CharField(choices=[('haut', 'Haut (15 000 XPF/mois)'), ('milieu', 'Milieu (10 000 XPF/mois)'), ('bas', 'Bas (5 000 XPF/mois)')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('traite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demande de pub',
                'verbose_name_plural': 'Demandes de pub',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pubs/')),
                ('image_url', models.URLField(blank=True, help_text="URL externe si pas d'upload")),
                ('lien', models.URLField(blank=True)),
                ('emplacement', models.CharField(choices=[('haut', 'Haut (15 000 XPF/mois)'), ('milieu', 'Milieu (10 000 XPF/mois)'), ('bas', 'Bas (5 000 XPF/mois)')], max_length=20)),
                ('prix', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('client_nom', models.CharField(blank=True, max_length=150)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_tel', models.CharField(blank=True, max_length=20)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Publicité',
                'verbose_name_plural': 'Publicités',
                'ordering': ['emplacement', '-actif'],
            },
        ),
    ]
