# Generated by Django 5.2.11 on 2026-02-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepublicite',
            name='emplacement_souhaite',
            field=models.CharField(choices=[('billboard', 'Billboard header (25 000 XPF/mois)'), ('haut', 'Sidebar Haut (15 000 XPF/mois)'), ('milieu', 'Sidebar Milieu (10 000 XPF/mois)'), ('bas', 'Sidebar Bas (5 000 XPF/mois)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='emplacement',
            field=models.CharField(choices=[('billboard', 'Billboard header (25 000 XPF/mois)'), ('haut', 'Sidebar Haut (15 000 XPF/mois)'), ('milieu', 'Sidebar Milieu (10 000 XPF/mois)'), ('bas', 'Sidebar Bas (5 000 XPF/mois)')], max_length=20),
        ),
    ]
