# Generated by Django 5.2.11 on 2026-02-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0002_alter_demandepublicite_emplacement_souhaite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepublicite',
            name='emplacement_souhaite',
            field=models.CharField(choices=[('billboard', 'Billboard Haut (25\u202f000 XPF/mois)'), ('billboard_milieu', 'Billboard Milieu (15\u202f000 XPF/mois)'), ('haut', 'Sidebar Haut (10\u202f000 XPF/mois)'), ('milieu', 'Sidebar Milieu (7\u202f000 XPF/mois)'), ('bas', 'Sidebar Bas (5\u202f000 XPF/mois)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='emplacement',
            field=models.CharField(choices=[('billboard', 'Billboard Haut (25\u202f000 XPF/mois)'), ('billboard_milieu', 'Billboard Milieu (15\u202f000 XPF/mois)'), ('haut', 'Sidebar Haut (10\u202f000 XPF/mois)'), ('milieu', 'Sidebar Milieu (7\u202f000 XPF/mois)'), ('bas', 'Sidebar Bas (5\u202f000 XPF/mois)')], max_length=20),
        ),
    ]
