# Generated by Django 5.2.11 on 2026-03-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0003_add_billboard_milieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicite',
            name='duree_semaines',
            field=models.IntegerField(default=4, help_text='Durée achetée en semaines'),
        ),
        migrations.AddField(
            model_name='publicite',
            name='payment_ref',
            field=models.CharField(blank=True, help_text='Référence unique PayZen (vads_order_id)', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='publicite',
            name='payment_status',
            field=models.CharField(choices=[('none', '—'), ('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('expired', 'Expiré')], db_index=True, default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='publicite',
            name='payment_trans_id',
            field=models.CharField(blank=True, help_text='ID transaction retourné par PayZen', max_length=64),
        ),
        migrations.AlterField(
            model_name='demandepublicite',
            name='emplacement_souhaite',
            field=models.CharField(choices=[('billboard', 'Billboard plein ecran (25 000 XPF/mois)'), ('strip_1', 'Strip 1 - Apres Promos (8 000 XPF/mois)'), ('strip_2', 'Strip 2 - Milieu page (8 000 XPF/mois)'), ('strip_3', 'Strip 3 - Fin de page (8 000 XPF/mois)'), ('haut', 'Sidebar Haut (60 000 XPF/mois)'), ('milieu', 'Sidebar Milieu (40 000 XPF/mois)'), ('bas', 'Sidebar Bas (20 000 XPF/mois)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='emplacement',
            field=models.CharField(choices=[('billboard', 'Billboard plein ecran (25 000 XPF/mois)'), ('strip_1', 'Strip 1 - Apres Promos (8 000 XPF/mois)'), ('strip_2', 'Strip 2 - Milieu page (8 000 XPF/mois)'), ('strip_3', 'Strip 3 - Fin de page (8 000 XPF/mois)'), ('haut', 'Sidebar Haut (60 000 XPF/mois)'), ('milieu', 'Sidebar Milieu (40 000 XPF/mois)'), ('bas', 'Sidebar Bas (20 000 XPF/mois)')], max_length=20),
        ),
    ]
