# Generated by Django 5.2.11 on 2026-03-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0004_payment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepublicite',
            name='emplacement_souhaite',
            field=models.CharField(choices=[('billboard', 'Billboard plein écran (100 000 XPF/mois)'), ('strip_1', 'Strip 1 - Après Promos (8 000 XPF/mois)'), ('strip_2', 'Strip 2 - Milieu page (8 000 XPF/mois)'), ('strip_3', 'Strip 3 - Fin de page (8 000 XPF/mois)'), ('haut', 'Sidebar Haut (40 000 XPF/mois)'), ('milieu', 'Sidebar Milieu (28 000 XPF/mois)'), ('bas', 'Sidebar Bas (20 000 XPF/mois)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='emplacement',
            field=models.CharField(choices=[('billboard', 'Billboard plein écran (100 000 XPF/mois)'), ('strip_1', 'Strip 1 - Après Promos (8 000 XPF/mois)'), ('strip_2', 'Strip 2 - Milieu page (8 000 XPF/mois)'), ('strip_3', 'Strip 3 - Fin de page (8 000 XPF/mois)'), ('haut', 'Sidebar Haut (40 000 XPF/mois)'), ('milieu', 'Sidebar Milieu (28 000 XPF/mois)'), ('bas', 'Sidebar Bas (20 000 XPF/mois)')], max_length=20),
        ),
    ]
